### ISSUE TITLE
Optional Options and Option Choices

### ISSUE THREAD

**Issue by Zone-Infinity** [ruffrick/jda-commands#2]
How do I make the options optional like we do in jda using `OptionData.setRequired(false)` ?
Can we add choices using the annotations ?

**Comment by ruffrick** [comment]
To make any option non-required, simply mark the parameter in the function as nullable and to add choices use an enum as the parameter type:
```kt
@Command
class ChooseCommand : SlashCommand() {
    @Command
    fun choose(event: SlashCommandInteractionEvent, @Option choice: Choice?) {
        event.reply(choice?.name ?: "Nothing").queue()
    }
}

enum class Choice(private val optionName: String) {
    ONE("Choice One!"),
    TWO("Choice Two!"),
    THREE("Choice Three!");

    override fun toString() = this.optionName
}
```
This will register as `/choose` with an optional argument `choice` that supports the choices `Choice One!`, `Choice Two!` and `Choice Three!`. When registering the options, it calls `toString()`, hence these names instead of `ONE`, `TWO` and `THREE`.
