### ISSUE TITLE
Buttons Dont Work

### ISSUE THREAD

**Issue by Crspy2** [ruffrick/jda-commands#4]
When I interact with a button, I get a `java.lang.IllegalArgumentException: Unknown button bad` error. Is there a fix?

Code:
@Command
class MoodCommand : SlashCommand() {
    @Command
    fun mood(event: SlashCommandInteractionEvent) {
        event.reply("How are you?").addActionRow(
            success("good", "Good"),
            danger("bad", "Bad")
        ).queue()
    }
    
    @Button("good")
    fun good(event: ButtonInteractionEvent) {
        event.editMessage("That's good to hear!").setActionRows().queue()
    }

    @Button("bad")
    fun bad(event: ButtonInteractionEvent) {
        event.editMessage("Oh no! Here, have some \uD83C\uDF68!").setActionRows().queue()
    }
}

**Comment by ruffrick** [comment]
From some quick testing I did with the Versions specified in the `build.gradle.kts` (JDA version 5.0.0-alpha.9 and jda-kotlinx version b19aded) it appeared to work fine, that Exception is usually only thrown when there is no function associated with the ID of an incoming button event.

I also won't be doing any work on this library in the current state, since I'm waiting for JDA to reach an (at least somewhat) stable 5.0.0 release before continuing work on this. Once that is released I'll look into updating everything and doing some more testing.
